In [1]:
import tensorflow as tf 
import numpy as np 
import matplotlib.pyplot as plt 


In [3]:
const_a = tf.constant([[1,2,3,4]], shape=[2,2], dtype=tf.int32) # sample array
print(const_a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
# Tensorflow zeros

zero_bee = tf.zeros(shape=[2,3], dtype=tf.int16) # create 2x3 matrix with 0's. 
print(zero_bee)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int16)


In [5]:
# Tensorflow fill
Ten_fill = tf.fill([3,3], 8) # 8 will be filled in the matrix
print(Ten_fill)

tf.Tensor(
[[8 8 8]
 [8 8 8]
 [8 8 8]], shape=(3, 3), dtype=int32)


In [7]:
# Tensorflow random

random_arr = tf.random.normal([5.5], mean=0, stddev= 1.0, seed=1) # view data
random_arr.numpy()


InvalidArgumentError: Value for attr 'T' of float is not in the list of allowed values: int32, int64
	; NodeDef: {{node RandomStandardNormal}}; Op<name=RandomStandardNormal; signature=shape:T -> output:dtype; attr=seed:int,default=0; attr=seed2:int,default=0; attr=dtype:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=T:type,allowed=[DT_INT32, DT_INT64]; is_stateful=true> [Op:RandomStandardNormal]